--Setting the materialization to 'table' for this model
{{ config(materialized='table') }}

WITH CUSTOMER_ORDERS AS(
    SELECT
        C.CUSTOMERID,
        CONCAT(C.FIRSTNAME, ' ', C.LASTNAME) AS CUSTOMER_NAME,
        COUNT(O.ORDERID) AS TOTAL_ORDERS
    FROM L1_LANDING.CUSTOMERS C
    JOIN L1_LANDING.ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
    GROUP BY C.CUSTOMERID, CUSTOMER_NAME
    ORDER BY TOTAL_ORDERS DESC
)
SELECT
    CUSTOMERID,
    CUSTOMER_NAME,
    TOTAL_ORDERS
FROM CUSTOMER_ORDERS